package: 
  name: genmine
  version : 1.0.6.2

source:
  git_url: "https://github.com/Changwanseo/GenMine.git"
  git_rev: v1.0.6.2

build:
  number: 0
  noarch: python

requirements:
  build:
    - python >=3
    - pandas
    - biopython
    - openpyxl
    - xlrd
    - numpy >=1.17
    - xmltodict
    - pytz
    - python-dateutil
  host:
    - python >=3
  run:
    - python >=3

test:
  commands:
    - GenMine -h &> /dev/null

about:
  home: https://github.com/Changwanseo/GenMine
  summary: "GenBank Miner for Taxonomists"
  license: "GPL3"
  license_file: "LICENSE"