{% set name = "GenMine" %}
{% set version = "1.0.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/GenMine-{{ version }}.tar.gz
  sha256: 083dcede4a4061819ea7e6cadda7d5ebf5c50cc44c66ef09cf6fe4cd682e6f66

build:
  entry_points:
    - GenMine = GenMine.main:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - biopython
    - pandas
    - openpyxl
    - xlrd
    - numpy
    - xmltodict
    - pytz
    - python-dateutil

test:
  imports:
    - GenMine
  commands:
    - pip check
    - GenMine --help
  requires:
    - pip

about:
  home: https://github.com/Changwanseo/GenMine
  summary: GenBank data miner for fungal taxonomists
  license: GPL-3.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - Changwanseo
