{% set name = "GenMine" %}
{% set version = "1.0.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/GenMine-{{ version }}.tar.gz
  sha256: 537d703a28f2cb68971a4c1e10707f06adcdbaf7d4c92a5a680bda8eab6f3971

build:
  entry_points:
    - GenMine = GenMine.main:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - biopython
    - pandas
    - openpyxl
    - xlrd
    - numpy
    - xmltodict
    - pytz
    - python-dateutil

test:
  imports:
    - GenMine
  commands:
    - pip check
    - GenMine --help
  requires:
    - pip

about:
  home: https://github.com/Changwanseo/GenMine
  summary: GenBank data miner for fungal taxonomists
  license: GPL-3.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - Changwanseo
